import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import './globals.css'
import { Footer, Header } from '@/widgets'
import { LenisScrollProvider } from '@/widgets/providers'

const groteskSans = Space_Grotesk({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${groteskSans.className} antialiased relative`}>
        <LenisScrollProvider>
          <Header />
          {children}
          <Footer />
        </LenisScrollProvider>
      </body>
    </html>
  )
}
